// Regenerates packages/web/src/brand.ts: the Truplexy wordmark as two tiny inline PNGs
// (dark text for light themes, light text for dark), so the widget makes no extra request.
//
//   node scripts/brand-assets.mjs
//
// Needs `sharp`, which the marketing site already installs (found by walking up to ../node_modules).
import { writeFileSync } from 'node:fs';
import sharp from 'sharp';

const HEIGHT = 32; // drawn at 16px, so 2x for sharp screens
const sources = {
  WORDMARK_ON_LIGHT: new URL('../../src/assets/brand/wordmark-dark.png', import.meta.url),
  WORDMARK_ON_DARK: new URL('../../src/assets/brand/wordmark-light.png', import.meta.url),
};

let out = `// Generated by scripts/brand-assets.mjs from src/assets/brand. Do not edit.\n`;
for (const [name, url] of Object.entries(sources)) {
  const trimmed = await sharp(url.pathname.replace(/^\/([A-Za-z]:)/, '$1')).trim({ threshold: 8 }).toBuffer();
  const png = await sharp(trimmed).resize({ height: HEIGHT }).png({ palette: true, quality: 90, effort: 10, colours: 32 }).toBuffer({ resolveWithObject: true });
  console.log(`${name}: ${png.info.width}x${png.info.height}, ${png.data.length} bytes`);
  out += `export const ${name} = { src: 'data:image/png;base64,${png.data.toString('base64')}', width: ${png.info.width}, height: ${png.info.height} };\n`;
}
writeFileSync(new URL('../packages/web/src/brand.ts', import.meta.url), out);
